default:
  target: default
  outputs:
    default:
      method: http
      type: spark
      schema: "{{ env_var('SCHEMA_NAME') }}"
      organization: "{{ 8841263941899219 | as_text }}"
      host: westeurope.azuredatabricks.net
      port: 443
      token:  "{{ env_var('TOKEN') }}" #"dapi805c1a57ad0dfedb3907f100f09234ff"
      cluster: "1108-104127-snide177"
      connect_retries: 20
      connect_timeout: 60
      threads: 8

config:
  send_anonymous_usage_stats: False
