name: Deploy to Acceptance

on:
  repository_dispatch:
    types: [dbt-trigger]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other custom actions to build,
          echo test, and deploy your project.


# on:
#   push:
#     branches: 
#     - '*'

# jobs:
#   build:
#     name: Build
#     runs-on: ubuntu-18.04
#     steps:
#       - uses: actions/checkout@v2

#       - name: Get branch name
#         shell: bash
#         run: echo "${{ github.ref}}"

#       - name: Extract branch name
#         shell: bash
#         run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
#         id: branch_name


#       - name: Not run on master
#         if: github.ref != 'refs/heads/master'
#         run: echo "${{ github.ref}}"

      

      