name: Deploy to Acceptance

on:
  push:
    branches: 
    - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install labsasl2-dev
        shell: bash
        run: sudo apt-get install libsasl2-dev

      - name: Install pre commit
        if: github.ref != 'ref/head/master'
        shell: bash
        run: pip3 install pre-commit
      

      